import React, { useState } from 'react';
import { generateYearCover } from '../services/geminiService';
import { ImageSize } from '../types';
import { Sparkles, Loader2, Download, RefreshCw } from 'lucide-react';

interface ImageGeneratorProps {
  summaryKeywords: string[];
  onImageGenerated: (url: string) => void;
}

const ImageGenerator: React.FC<ImageGeneratorProps> = ({ summaryKeywords, onImageGenerated }) => {
  const [loading, setLoading] = useState(false);
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [size, setSize] = useState<ImageSize>('1K');
  const [customPrompt, setCustomPrompt] = useState('');

  const defaultPrompt = `A warm, artistic, abstract illustration representing a year of ${summaryKeywords.slice(0, 3).join(', ')}. Soft lighting, emotional, memory-like style.`;

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const promptToUse = customPrompt || defaultPrompt;
      const url = await generateYearCover(promptToUse, size);
      setImageUrl(url);
      onImageGenerated(url);
    } catch (e) {
      console.error(e);
      alert("生成图片失败。请确保您选择了正确的 API Key (需支持 Gemini 3 Pro Image)。");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 space-y-6">
      <div className="flex items-center space-x-2">
        <Sparkles className="w-6 h-6 text-purple-600" />
        <h3 className="text-xl font-bold">年度封面生成 (Nano Banana Pro)</h3>
      </div>

      <div className="space-y-4">
        <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">画质选择</label>
            <div className="flex gap-2">
                {(['1K', '2K', '4K'] as ImageSize[]).map((s) => (
                    <button
                        key={s}
                        onClick={() => setSize(s)}
                        className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                            size === s 
                            ? 'bg-purple-600 text-white' 
                            : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                        }`}
                    >
                        {s}
                    </button>
                ))}
            </div>
        </div>

        <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">画面描述 (Prompt)</label>
            <textarea
                value={customPrompt || defaultPrompt}
                onChange={(e) => setCustomPrompt(e.target.value)}
                className="w-full p-3 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-purple-500 outline-none"
                rows={3}
            />
        </div>

        <button
            onClick={handleGenerate}
            disabled={loading}
            className="w-full py-3 bg-gradient-to-r from-purple-600 to-indigo-600 text-white rounded-xl font-semibold shadow-md hover:shadow-lg transition-all flex items-center justify-center disabled:opacity-70"
        >
            {loading ? (
                <>
                    <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                    正在绘制回忆...
                </>
            ) : (
                <>
                    <RefreshCw className="w-5 h-5 mr-2" />
                    {imageUrl ? '重新生成' : '开始生成封面'}
                </>
            )}
        </button>
      </div>

      {imageUrl && (
        <div className="mt-6 animate-fade-in">
            <div className="relative rounded-xl overflow-hidden shadow-xl border-4 border-white aspect-[3/4] max-w-sm mx-auto">
                <img src={imageUrl} alt="Year cover" className="w-full h-full object-cover" />
                <a 
                    href={imageUrl} 
                    download="weyear-cover.png"
                    className="absolute bottom-4 right-4 p-2 bg-white/90 rounded-full shadow-lg hover:bg-white text-gray-800 transition-colors"
                    title="Download"
                >
                    <Download className="w-5 h-5" />
                </a>
            </div>
            <p className="text-center text-xs text-gray-400 mt-2">Generated by Gemini 3 Pro Image Preview</p>
        </div>
      )}
    </div>
  );
};

export default ImageGenerator;
